export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const AUTHORIZE_USER_FAILURE = 'AUTHORIZE_USER_FAILURE';
export const AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS';

export const INITIALIZE_OPEN_API = 'INITIALIZE_OPEN_API';
